"""Create the complete OpenSLT schema.

Revision ID: 0001
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from app.core.types import JSONText

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


INDEXES = (
    ("ix_t_artifacts_artifact_type", "t_artifacts", ["artifact_type"], False, {}),
    ("ix_t_artifacts_run_id", "t_artifacts", ["run_id"], False, {}),
    ("ix_t_audit_logs_action", "t_audit_logs", ["action"], False, {}),
    ("ix_t_audit_logs_actor_id", "t_audit_logs", ["actor_id"], False, {}),
    ("ix_t_audit_logs_created_at", "t_audit_logs", ["created_at"], False, {}),
    ("ix_t_audit_logs_object_id", "t_audit_logs", ["object_id"], False, {}),
    ("ix_t_audit_logs_object_type", "t_audit_logs", ["object_type"], False, {}),
    ("ix_t_audit_logs_trace_id", "t_audit_logs", ["trace_id"], False, {}),
    ("ix_t_configuration_capture_items_item_key", "t_configuration_capture_items", ["item_key"], False, {}),
    ("ix_t_configuration_capture_items_snapshot_id", "t_configuration_capture_items", ["snapshot_id"], False, {}),
    ("ix_t_configuration_capture_items_status", "t_configuration_capture_items", ["status"], False, {}),
    ("ix_t_configuration_capture_snapshots_resource_id", "t_configuration_capture_snapshots", ["resource_id"], False, {}),
    ("ix_t_configuration_capture_snapshots_run_id", "t_configuration_capture_snapshots", ["run_id"], False, {}),
    ("ix_t_configuration_capture_snapshots_run_step_id", "t_configuration_capture_snapshots", ["run_step_id"], False, {}),
    ("ix_t_configuration_capture_snapshots_scenario_id", "t_configuration_capture_snapshots", ["scenario_id"], False, {}),
    ("ix_t_configuration_capture_snapshots_scope", "t_configuration_capture_snapshots", ["scope"], False, {}),
    ("ix_t_configuration_capture_snapshots_source_type", "t_configuration_capture_snapshots", ["source_type"], False, {}),
    ("ix_t_configuration_capture_snapshots_status", "t_configuration_capture_snapshots", ["status"], False, {}),
    ("ix_t_configuration_capture_snapshots_workflow_node_id", "t_configuration_capture_snapshots", ["workflow_node_id"], False, {}),
    ("ix_t_configuration_capture_snapshots_workflow_version_id", "t_configuration_capture_snapshots", ["workflow_version_id"], False, {}),
    ("ix_t_contract_data_files_checksum", "t_contract_data_files", ["checksum"], False, {}),
    ("ix_t_contract_data_files_contract_type", "t_contract_data_files", ["contract_type"], False, {}),
    ("ix_t_contract_data_files_created_by", "t_contract_data_files", ["created_by"], False, {}),
    ("ix_t_contract_data_files_database_resource_id", "t_contract_data_files", ["database_resource_id"], False, {}),
    ("ix_t_contract_data_files_order_resource_id", "t_contract_data_files", ["order_resource_id"], False, {}),
    ("ix_t_contract_data_files_quote_date", "t_contract_data_files", ["quote_date"], False, {}),
    ("ix_t_contract_data_files_scenario_id", "t_contract_data_files", ["scenario_id"], False, {}),
    ("ix_t_contract_data_files_workflow_node_id", "t_contract_data_files", ["workflow_node_id"], False, {}),
    (
        "uq_t_contract_data_files_node_name_checksum",
        "t_contract_data_files",
        ["workflow_node_id", "filename", "checksum"],
        True,
        {"mysql_length": {"filename": 120, "checksum": 64}},
    ),
    ("ix_t_database_update_confirmations_actor_id", "t_database_update_confirmations", ["actor_id"], False, {}),
    ("ix_t_database_update_confirmations_expires_at", "t_database_update_confirmations", ["expires_at"], False, {}),
    ("ix_t_database_update_confirmations_resource_id", "t_database_update_confirmations", ["resource_id"], False, {}),
    ("ix_t_database_update_confirmations_sql_fingerprint", "t_database_update_confirmations", ["sql_fingerprint"], False, {}),
    ("ix_t_database_update_confirmations_status", "t_database_update_confirmations", ["status"], False, {}),
    ("ix_t_log_records_run_created", "t_log_records", ["run_id", "created_at"], False, {}),
    ("ix_t_log_records_trace_created", "t_log_records", ["trace_id", "created_at"], False, {}),
    ("ix_t_log_records_created_at", "t_log_records", ["created_at"], False, {}),
    ("ix_t_log_records_event", "t_log_records", ["event"], False, {}),
    ("ix_t_log_records_level", "t_log_records", ["level"], False, {}),
    ("ix_t_log_records_log_type", "t_log_records", ["log_type"], False, {}),
    ("ix_t_log_records_run_id", "t_log_records", ["run_id"], False, {}),
    ("ix_t_log_records_source", "t_log_records", ["source"], False, {}),
    ("ix_t_log_records_step_id", "t_log_records", ["step_id"], False, {}),
    ("ix_t_log_records_trace_id", "t_log_records", ["trace_id"], False, {}),
    ("ix_t_log_records_user_id", "t_log_records", ["user_id"], False, {}),
    ("ix_t_metrics_run_id", "t_metrics", ["run_id"], False, {}),
    ("ix_t_refresh_tokens_user_id", "t_refresh_tokens", ["user_id"], False, {}),
    ("ix_t_resource_locks_lease_expires_at", "t_resource_locks", ["lease_expires_at"], False, {}),
    ("ix_t_resource_locks_released_at", "t_resource_locks", ["released_at"], False, {}),
    ("ix_t_resource_locks_resource_id", "t_resource_locks", ["resource_id"], False, {}),
    ("ix_t_resource_locks_run_id", "t_resource_locks", ["run_id"], False, {}),
    ("ix_t_resources_business_code", "t_resources", ["business_code"], False, {}),
    ("ix_t_resources_name", "t_resources", ["name"], False, {}),
    ("ix_t_resources_resource_type", "t_resources", ["resource_type"], False, {}),
    ("ix_t_run_steps_run_id", "t_run_steps", ["run_id"], False, {}),
    ("ix_t_run_steps_workflow_node_id", "t_run_steps", ["workflow_node_id"], False, {}),
    ("ix_t_scenario_workflow_nodes_node_type", "t_scenario_workflow_nodes", ["node_type"], False, {}),
    ("ix_t_scenario_workflow_nodes_workflow_version_id", "t_scenario_workflow_nodes", ["workflow_version_id"], False, {}),
    ("ix_t_scenario_workflow_versions_created_by", "t_scenario_workflow_versions", ["created_by"], False, {}),
    ("ix_t_scenario_workflow_versions_scenario_id", "t_scenario_workflow_versions", ["scenario_id"], False, {}),
    ("ix_t_scenario_workflow_versions_status", "t_scenario_workflow_versions", ["status"], False, {}),
    ("ix_t_test_plans_business_code", "t_test_plans", ["business_code"], False, {}),
    ("ix_t_test_plans_name", "t_test_plans", ["name"], False, {}),
    ("ix_t_test_runs_business_code", "t_test_runs", ["business_code"], False, {}),
    ("ix_t_test_runs_created_by", "t_test_runs", ["created_by"], False, {}),
    ("ix_t_test_runs_plan_id", "t_test_runs", ["plan_id"], False, {}),
    ("ix_t_test_runs_run_number", "t_test_runs", ["run_number"], True, {}),
    ("ix_t_test_runs_scenario_id", "t_test_runs", ["scenario_id"], False, {}),
    ("ix_t_test_runs_status", "t_test_runs", ["status"], False, {}),
    ("ix_t_test_runs_trace_id", "t_test_runs", ["trace_id"], False, {}),
    ("ix_t_test_runs_workflow_version_id", "t_test_runs", ["workflow_version_id"], False, {}),
    ("ix_t_test_scenarios_is_archived", "t_test_scenarios", ["is_archived"], False, {}),
    ("ix_t_test_scenarios_plan_id", "t_test_scenarios", ["plan_id"], False, {}),
    ("ix_t_test_scenarios_scenario_type", "t_test_scenarios", ["scenario_type"], False, {}),
    ("ix_t_test_scenarios_workflow_status", "t_test_scenarios", ["workflow_status"], False, {}),
    ("ix_t_users_role", "t_users", ["role"], False, {}),
    ("ix_t_users_username", "t_users", ["username"], True, {}),
)


TABLES_IN_CREATION_ORDER = (
    "t_users",
    "t_business_types",
    "t_resources",
    "t_refresh_tokens",
    "t_database_update_confirmations",
    "t_test_plans",
    "t_test_scenarios",
    "t_scenario_workflow_versions",
    "t_scenario_workflow_nodes",
    "t_test_runs",
    "t_run_steps",
    "t_configuration_capture_snapshots",
    "t_configuration_capture_items",
    "t_contract_data_files",
    "t_log_records",
    "t_artifacts",
    "t_metrics",
    "t_verdicts",
    "t_resource_locks",
    "t_audit_logs",
)


def _is_sqlite() -> bool:
    return op.get_context().dialect.name == "sqlite"


def upgrade() -> None:
    op.create_table(
        "t_users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("username", sa.String(64), nullable=False),
        sa.Column("display_name", sa.String(128), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.String(32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "t_business_types",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("code", sa.String(32), nullable=False),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "t_resources",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("resource_type", sa.String(32), nullable=False),
        sa.Column("business_code", sa.String(32), nullable=False),
        sa.Column("host", sa.String(255), nullable=False),
        sa.Column("ssh_port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(128), nullable=False),
        sa.Column("auth_type", sa.String(16), nullable=False),
        sa.Column("encrypted_password", sa.Text()),
        sa.Column("encrypted_private_key", sa.Text()),
        sa.Column("database_engine", sa.String(32)),
        sa.Column("database_connection_mode", sa.String(32)),
        sa.Column("database_host", sa.String(255)),
        sa.Column("database_port", sa.Integer()),
        sa.Column("database_names", JSONText()),
        sa.Column("database_username", sa.String(128)),
        sa.Column("encrypted_database_password", sa.Text()),
        sa.Column("database_tls_enabled", sa.Boolean(), nullable=False),
        sa.Column("remote_path", sa.String(512), nullable=False),
        sa.Column("capabilities", JSONText(), nullable=False),
        sa.Column("version_info", sa.String(255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("health_status", sa.String(32), nullable=False),
        sa.Column("health_checked_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_table(
        "t_refresh_tokens",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["t_users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("fingerprint"),
    )
    op.create_table(
        "t_database_update_confirmations",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("database_name", sa.String(128), nullable=False),
        sa.Column("table_name", sa.String(255), nullable=False),
        sa.Column("sql_fingerprint", sa.String(64), nullable=False),
        sa.Column("estimated_rows", sa.Integer(), nullable=False),
        sa.Column("actual_rows", sa.Integer()),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(["resource_id"], ["t_resources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["actor_id"], ["t_users.id"], ondelete="CASCADE"),
    )
    op.create_table(
        "t_test_plans",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("business_code", sa.String(32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("default_resource_ids", JSONText(), nullable=False),
        sa.Column("config_version", sa.String(64), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["t_users.id"]),
    )

    scenario_constraints = []
    if _is_sqlite():
        scenario_constraints.extend(
            [
                sa.ForeignKeyConstraint(
                    ["draft_workflow_version_id"],
                    ["t_scenario_workflow_versions.id"],
                    name="fk_test_scenarios_draft_workflow_version_id",
                    ondelete="SET NULL",
                ),
                sa.ForeignKeyConstraint(
                    ["published_workflow_version_id"],
                    ["t_scenario_workflow_versions.id"],
                    name="fk_test_scenarios_published_workflow_version_id",
                    ondelete="SET NULL",
                ),
            ]
        )
    op.create_table(
        "t_test_scenarios",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("scenario_type", sa.String(64), nullable=False),
        sa.Column("config_version", sa.String(64), nullable=False),
        sa.Column("expected_artifacts", JSONText(), nullable=False),
        sa.Column("default_resource_ids", JSONText(), nullable=False),
        sa.Column("required_resource_types", JSONText(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("workflow_status", sa.String(24), nullable=False),
        sa.Column("draft_workflow_version_id", sa.Integer()),
        sa.Column("published_workflow_version_id", sa.Integer()),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["t_test_plans.id"], ondelete="CASCADE"),
        *scenario_constraints,
    )
    op.create_table(
        "t_scenario_workflow_versions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(24), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("resource_ids", JSONText(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("published_by", sa.Integer()),
        sa.Column("published_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scenario_id"], ["t_test_scenarios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["t_users.id"]),
        sa.ForeignKeyConstraint(["published_by"], ["t_users.id"]),
        sa.UniqueConstraint("scenario_id", "version_no", name="uq_scenario_workflow_version"),
    )
    if not _is_sqlite():
        op.create_foreign_key(
            "fk_test_scenarios_draft_workflow_version_id",
            "t_test_scenarios",
            "t_scenario_workflow_versions",
            ["draft_workflow_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
        op.create_foreign_key(
            "fk_test_scenarios_published_workflow_version_id",
            "t_test_scenarios",
            "t_scenario_workflow_versions",
            ["published_workflow_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
    op.create_table(
        "t_scenario_workflow_nodes",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("workflow_version_id", sa.Integer(), nullable=False),
        sa.Column("node_key", sa.String(36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("node_type", sa.String(40), nullable=False),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("config", JSONText(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workflow_version_id"], ["t_scenario_workflow_versions.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("workflow_version_id", "node_key", name="uq_workflow_node_key"),
        sa.UniqueConstraint("workflow_version_id", "position", name="uq_workflow_node_position"),
    )
    op.create_table(
        "t_test_runs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("run_number", sa.String(40), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("workflow_version_id", sa.Integer()),
        sa.Column("business_code", sa.String(32), nullable=False),
        sa.Column("status", sa.String(40), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("resource_ids", JSONText(), nullable=False),
        sa.Column("config_snapshot", JSONText(), nullable=False),
        sa.Column("trace_id", sa.String(64), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("timeout_at", sa.DateTime(timezone=True)),
        sa.Column("error_code", sa.String(64)),
        sa.Column("error_message", sa.Text()),
        sa.Column("queue_reason", sa.Text()),
        sa.Column("paused_from", sa.String(40)),
        sa.Column("logs_complete", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["t_test_plans.id"]),
        sa.ForeignKeyConstraint(["scenario_id"], ["t_test_scenarios.id"]),
        sa.ForeignKeyConstraint(["workflow_version_id"], ["t_scenario_workflow_versions.id"]),
        sa.ForeignKeyConstraint(["created_by"], ["t_users.id"]),
    )
    op.create_table(
        "t_run_steps",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("workflow_node_id", sa.Integer()),
        sa.Column("code", sa.String(64), nullable=False),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("node_type", sa.String(40), nullable=False),
        sa.Column("config_snapshot", JSONText(), nullable=False),
        sa.Column("result_summary", JSONText(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(24), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("duration_ms", sa.Integer()),
        sa.Column("error_message", sa.Text()),
        sa.ForeignKeyConstraint(["run_id"], ["t_test_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_node_id"], ["t_scenario_workflow_nodes.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("run_id", "code", name="uq_run_step_code"),
    )
    op.create_table(
        "t_configuration_capture_snapshots",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("workflow_version_id", sa.Integer(), nullable=False),
        sa.Column("workflow_node_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer()),
        sa.Column("run_step_id", sa.Integer()),
        sa.Column("scope", sa.String(16), nullable=False),
        sa.Column("source_type", sa.String(24), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("database_name", sa.String(128)),
        sa.Column("status", sa.String(24), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text()),
        sa.Column("created_by", sa.Integer()),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(["scenario_id"], ["t_test_scenarios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_version_id"], ["t_scenario_workflow_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_node_id"], ["t_scenario_workflow_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["t_test_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_step_id"], ["t_run_steps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resource_id"], ["t_resources.id"]),
        sa.ForeignKeyConstraint(["created_by"], ["t_users.id"]),
    )
    op.create_table(
        "t_configuration_capture_items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("item_key", sa.String(128), nullable=False),
        sa.Column("item_label", sa.String(128), nullable=False),
        sa.Column("value_text", sa.Text()),
        sa.Column("source_reference", sa.Text(), nullable=False),
        sa.Column("raw_output", sa.Text(), nullable=False),
        sa.Column("exit_code", sa.Integer()),
        sa.Column("status", sa.String(24), nullable=False),
        sa.Column("error_message", sa.Text()),
        sa.ForeignKeyConstraint(["snapshot_id"], ["t_configuration_capture_snapshots.id"], ondelete="CASCADE"),
    )
    op.create_table(
        "t_contract_data_files",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("scenario_id", sa.Integer()),
        sa.Column("workflow_node_id", sa.Integer()),
        sa.Column("order_resource_id", sa.Integer(), nullable=False),
        sa.Column("database_resource_id", sa.Integer()),
        sa.Column("database_name", sa.String(128)),
        sa.Column("contract_type", sa.String(16), nullable=False),
        sa.Column("source_table", sa.String(128), nullable=False),
        sa.Column("filename", sa.String(255), nullable=False),
        sa.Column("remote_path", sa.String(1024), nullable=False),
        sa.Column("archive_path", sa.String(1024), nullable=False),
        sa.Column("quote_date", sa.String(32)),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(64), nullable=False),
        sa.Column("preview_rows", JSONText(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scenario_id"], ["t_test_scenarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workflow_node_id"], ["t_scenario_workflow_nodes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_resource_id"], ["t_resources.id"]),
        sa.ForeignKeyConstraint(["database_resource_id"], ["t_resources.id"]),
        sa.ForeignKeyConstraint(["created_by"], ["t_users.id"]),
    )
    op.create_table(
        "t_log_records",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("log_type", sa.String(32), nullable=False),
        sa.Column("level", sa.String(16), nullable=False),
        sa.Column("event", sa.String(128), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("trace_id", sa.String(64), nullable=False),
        sa.Column("user_id", sa.Integer()),
        sa.Column("run_id", sa.Integer()),
        sa.Column("step_id", sa.Integer()),
        sa.Column("source", sa.String(64), nullable=False),
        sa.Column("detail", JSONText(), nullable=False),
        sa.Column("artifact_path", sa.String(1024)),
        sa.Column("is_redacted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["t_users.id"]),
        sa.ForeignKeyConstraint(["run_id"], ["t_test_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["t_run_steps.id"], ondelete="SET NULL"),
    )
    op.create_table(
        "t_artifacts",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer()),
        sa.Column("artifact_type", sa.String(32), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("path", sa.String(1024), nullable=False),
        sa.Column("content_type", sa.String(128), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(64), nullable=False),
        sa.Column("is_immutable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["t_test_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["t_run_steps.id"], ondelete="SET NULL"),
    )
    op.create_table(
        "t_metrics",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(128), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(32), nullable=False),
        sa.Column("sample_count", sa.Integer()),
        sa.Column("detail", JSONText(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["t_test_runs.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("run_id", "name", name="uq_run_metric_name"),
    )
    op.create_table(
        "t_verdicts",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("final_result", sa.String(32)),
        sa.Column("issue_description", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("reviewed_by", sa.Integer()),
        sa.Column("reviewed_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["t_test_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["t_users.id"]),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "t_resource_locks",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True)),
        sa.Column("release_reason", sa.String(128)),
        sa.ForeignKeyConstraint(["resource_id"], ["t_resources.id"]),
        sa.ForeignKeyConstraint(["run_id"], ["t_test_runs.id"], ondelete="CASCADE"),
    )
    op.create_table(
        "t_audit_logs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("actor_id", sa.Integer()),
        sa.Column("action", sa.String(128), nullable=False),
        sa.Column("object_type", sa.String(64), nullable=False),
        sa.Column("object_id", sa.String(64)),
        sa.Column("result", sa.String(32), nullable=False),
        sa.Column("source_ip", sa.String(64)),
        sa.Column("user_agent", sa.String(512)),
        sa.Column("trace_id", sa.String(64), nullable=False),
        sa.Column("detail", JSONText(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["t_users.id"]),
    )

    for name, table_name, columns, unique, options in INDEXES:
        op.create_index(name, table_name, columns, unique=unique, **options)


def downgrade() -> None:
    if not _is_sqlite():
        op.drop_constraint(
            "fk_test_scenarios_published_workflow_version_id",
            "t_test_scenarios",
            type_="foreignkey",
        )
        op.drop_constraint(
            "fk_test_scenarios_draft_workflow_version_id",
            "t_test_scenarios",
            type_="foreignkey",
        )
    for table_name in reversed(TABLES_IN_CREATION_ORDER):
        op.drop_table(table_name)
